export const root: string;
export const column: string;
export const link: string;
export const image: string;
export const content: string;
export const banner: string;
export const date: string;
export const tags: string;
export const tag: string;
